-- MySQL Script generated by MySQL Workbench
-- Tue Jul 25 11:29:06 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kuvera108
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kuvera108
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kuvera108` DEFAULT CHARACTER SET utf8 ;
USE `kuvera108` ;

-- -----------------------------------------------------
-- Table `kuvera108`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kuvera108`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `kuvera108`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kuvera108`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);

CREATE USER 'root' IDENTIFIED BY 'Krishna1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
